### ISSUE TITLE
salve's gulp does not handle --jsdoc-private

### ISSUE THREAD

**Issue by lddubeau** [mangalam-research/salve#25]
This is what I get:

```
$ gulp --jsdoc-private gh-pages-build
[10:22:12] Requiring external module babel-core/register
[10:22:15] Using gulpfile ~/src/git-repos/salve/gulpfile.babel.js
[10:22:15] Starting 'copy-src'...
[10:22:15] Starting 'copy-readme'...
[10:22:15] Starting 'jison'...
[10:22:15] Finished 'jison' after 107 ms
[10:22:15] Finished 'copy-readme' after 110 ms
[10:22:15] Finished 'copy-src' after 197 ms
[10:22:15] Starting 'default'...
[10:22:15] Finished 'default' after 1.66 ms
```

What I should get is essentially the same output as running `gulp gh-pages-build`, except that the documentation should include what has been marked private.

For reference, `gulp gh-pages-build` does:

```
$ gulp gh-pages-build
[10:29:36] Requiring external module babel-core/register
[10:29:40] Using gulpfile ~/src/git-repos/salve/gulpfile.babel.js
[10:29:40] Starting 'check-jsdoc-version'...
[10:29:40] Finished 'check-jsdoc-version' after 214 ms
[10:29:40] Starting 'jsdoc'...
[10:29:40] Finished 'jsdoc' after 190 ms
[10:29:40] Starting 'gh-pages-build'...
[10:29:40] Finished 'gh-pages-build' after 106 ms
```

**Comment by bennettbuchanan** [comment]
When you add the ``--jsdoc-private`` option to the gulp command it
apparently executes the default gulp task (this also seems to be true for
the other arguments handled by the ArgumentParser object). If this method
of passing in task specific flags to ``gulp`` was working before, I am
having difficulty tracking down why it is broken now. I have consulted the
documentation for argparse, and the code all seems to be working properly
otherwise.

However, the man page for gulp refers to this method of passing in task
specific flags (
http://stackoverflow.com/questions/23023650/is-it-possible-to-pass-a-flag-to-gulp-to-have-it-run-tasks-in-different-ways).
This would mean passing in flags in this order: ``gulp gh-pages-build
--jsdoc-private``, and using the npm package yargs. Perhaps this is too
great a departure from the established approach.

Let me know how you think it would be best to proceed.

**Comment by bennettbuchanan** [comment]
When you add the `--jsdoc-private` option to the gulp command it
apparently executes the default gulp task (this also seems to be true for
the other arguments handled by the ArgumentParser object). If this method
of passing in task specific flags to `gulp` was working before, I am
having difficulty tracking down why it is broken now. I have consulted the
documentation for argparse, and the code all seems to be working properly
otherwise.

However, the man page for gulp refers to this method of passing in task
specific flags (http://stackoverflow.com/questions/23023650/is-it-possible-to-pass-a-flag-to-gulp-to-have-it-run-tasks-in-different-ways).
This would mean passing in flags in this order: `gulp gh-pages-build
--jsdoc-private`, and using the npm package yargs. Perhaps this is too
great a departure from the established approach.

Let me know how you think it would be best to proceed.

**Comment by lddubeau** [comment]
Ok, multiple things at play here. When I initially tried, I tried both `gulp --jsdoc-private gh-pages-build` and `gulp gh-pages-build --jsdoc-private` but I must not have looked carefully at the error message I get with the latter because the error message actually tells me what the issue is.

It works if I run `gulp gh-pages-build --jsdoc-private=1`. However, this is a bit annoying. Please check to see if there is a way to allow `--jsdoc-private` to be interpreted as `--jsdoc-private=1`. I would like to keep the option of doing `--jsdoc-private=0` to allow turning it off if something else turns it on by default. For instance the local configuration that is read by the gulpfile could turn it on by default. It would be nice to still have the possibility to turn it off on the command line.

The [`argparse`](https://www.npmjs.com/package/argparse) package is a port of Python's [`argparse`](https://docs.python.org/2/library/argparse.html#module-argparse) module so you may have to look at the Python documentation.

**Comment by bennettbuchanan** [comment]
By including `action: 'storeTrue',` where `--jsdoc-private` is added to the `ArgumentParser` object, `--jsdoc-private` is interpreted as `--jsdoc-private=1`. To build the documentation without the items marked private, run `gulp gh-pages-build`. Running `gulp clean` before rebuilding the gh-pages documentation is necessary.

Would you like me to push the change directly?

**Comment by lddubeau** [comment]
Yes, pull request please, once we've come to some solution.

AFAIK, `storeTrue` will not allow doing this: `gulp gh-pages-build --jsdoc-private --jsdoc-private=0`. This looks silly, and indeed only someone confused would type this at the command line but a functional equivalent of the above can happen if:

* `gulp.local.js` turns on `jsdoc-private` by default. Issuing `gulp gh-pages-build --jsdoc-private=0` would then make sense to turn off the default.

* `gulp` is invoked as part of a toolchain. The command line may pass through multiple hands. If an earlier one passes `--jsdoc-private`, a later one may need to turn it off.

If I am wrong about `storeTrue` (which is possible), please let me know. Otherwise, check to make sure there is no way to allow for both `--jsdoc-private` to turn in on and `--jsdoc-private=0` to turn it off. (It is fine is `--jsdoc-private=1` is allowed. I just don't want to be forced to do `--jsdoc-private=1` at the command line.)

Actually, as I'm typing this, I'm thinking a better solution than what I'm suggesting above would be to allow `--jsdoc-private` to include private entities in the documentation and `--no-jsdoc-private` to turn off `--jsdoc-private`. I'm thinking this will mean splitting `--jsdoc-private` into two options and having the latter do something like having the action `storeFalse` with the destination `jsdoc_private`. (I don't know if `storeFalse` exists.)

**Comment by bennettbuchanan** [comment]
I was actually thinking of the same possibility because `storeFalse` does indeed exist. I have made a pull request with that change and commented the specifics there.
